# Generated by Django 4.1 on 2022-09-17 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0005_alter_watchlist_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
